insert into T_BASE_FUNCTION(BAF_ID_C) values('ADMIN');

insert into T_LOCALE(LOC_ID_C) values('sq_AL');
insert into T_LOCALE(LOC_ID_C) values('sq');
insert into T_LOCALE(LOC_ID_C) values('ar_DZ');
insert into T_LOCALE(LOC_ID_C) values('ar_BH');
insert into T_LOCALE(LOC_ID_C) values('ar_EG');
insert into T_LOCALE(LOC_ID_C) values('ar_IQ');
insert into T_LOCALE(LOC_ID_C) values('ar_JO');
insert into T_LOCALE(LOC_ID_C) values('ar_KW');
insert into T_LOCALE(LOC_ID_C) values('ar_LB');
insert into T_LOCALE(LOC_ID_C) values('ar_LY');
insert into T_LOCALE(LOC_ID_C) values('ar_MA');
insert into T_LOCALE(LOC_ID_C) values('ar_OM');
insert into T_LOCALE(LOC_ID_C) values('ar_QA');
insert into T_LOCALE(LOC_ID_C) values('ar_SA');
insert into T_LOCALE(LOC_ID_C) values('ar_SD');
insert into T_LOCALE(LOC_ID_C) values('ar_SY');
insert into T_LOCALE(LOC_ID_C) values('ar_TN');
insert into T_LOCALE(LOC_ID_C) values('ar_AE');
insert into T_LOCALE(LOC_ID_C) values('ar_YE');
insert into T_LOCALE(LOC_ID_C) values('ar');
insert into T_LOCALE(LOC_ID_C) values('be_BY');
insert into T_LOCALE(LOC_ID_C) values('be');
insert into T_LOCALE(LOC_ID_C) values('bg_BG');
insert into T_LOCALE(LOC_ID_C) values('bg');
insert into T_LOCALE(LOC_ID_C) values('ca_ES');
insert into T_LOCALE(LOC_ID_C) values('ca');
insert into T_LOCALE(LOC_ID_C) values('zh_CN');
insert into T_LOCALE(LOC_ID_C) values('zh_HK');
insert into T_LOCALE(LOC_ID_C) values('zh_SG');
insert into T_LOCALE(LOC_ID_C) values('zh_TW');
insert into T_LOCALE(LOC_ID_C) values('zh');
insert into T_LOCALE(LOC_ID_C) values('hr_HR');
insert into T_LOCALE(LOC_ID_C) values('hr');
insert into T_LOCALE(LOC_ID_C) values('cs_CZ');
insert into T_LOCALE(LOC_ID_C) values('cs');
insert into T_LOCALE(LOC_ID_C) values('da_DK');
insert into T_LOCALE(LOC_ID_C) values('da');
insert into T_LOCALE(LOC_ID_C) values('nl_BE');
insert into T_LOCALE(LOC_ID_C) values('nl_NL');
insert into T_LOCALE(LOC_ID_C) values('nl');
insert into T_LOCALE(LOC_ID_C) values('en_AU');
insert into T_LOCALE(LOC_ID_C) values('en_CA');
insert into T_LOCALE(LOC_ID_C) values('en_IN');
insert into T_LOCALE(LOC_ID_C) values('en_IE');
insert into T_LOCALE(LOC_ID_C) values('en_MT');
insert into T_LOCALE(LOC_ID_C) values('en_NZ');
insert into T_LOCALE(LOC_ID_C) values('en_PH');
insert into T_LOCALE(LOC_ID_C) values('en_SG');
insert into T_LOCALE(LOC_ID_C) values('en_ZA');
insert into T_LOCALE(LOC_ID_C) values('en_GB');
insert into T_LOCALE(LOC_ID_C) values('en_US');
insert into T_LOCALE(LOC_ID_C) values('en');
insert into T_LOCALE(LOC_ID_C) values('et_EE');
insert into T_LOCALE(LOC_ID_C) values('et');
insert into T_LOCALE(LOC_ID_C) values('fi_FI');
insert into T_LOCALE(LOC_ID_C) values('fi');
insert into T_LOCALE(LOC_ID_C) values('fr_BE');
insert into T_LOCALE(LOC_ID_C) values('fr_CA');
insert into T_LOCALE(LOC_ID_C) values('fr_FR');
insert into T_LOCALE(LOC_ID_C) values('fr_LU');
insert into T_LOCALE(LOC_ID_C) values('fr_CH');
insert into T_LOCALE(LOC_ID_C) values('fr');
insert into T_LOCALE(LOC_ID_C) values('de_AT');
insert into T_LOCALE(LOC_ID_C) values('de_DE');
insert into T_LOCALE(LOC_ID_C) values('de_LU');
insert into T_LOCALE(LOC_ID_C) values('de_CH');
insert into T_LOCALE(LOC_ID_C) values('de');
insert into T_LOCALE(LOC_ID_C) values('el_CY');
insert into T_LOCALE(LOC_ID_C) values('el_GR');
insert into T_LOCALE(LOC_ID_C) values('el');
insert into T_LOCALE(LOC_ID_C) values('iw_IL');
insert into T_LOCALE(LOC_ID_C) values('iw');
insert into T_LOCALE(LOC_ID_C) values('hi_IN');
insert into T_LOCALE(LOC_ID_C) values('hu_HU');
insert into T_LOCALE(LOC_ID_C) values('hu');
insert into T_LOCALE(LOC_ID_C) values('is_IS');
insert into T_LOCALE(LOC_ID_C) values('is');
insert into T_LOCALE(LOC_ID_C) values('in_ID');
insert into T_LOCALE(LOC_ID_C) values('in');
insert into T_LOCALE(LOC_ID_C) values('ga_IE');
insert into T_LOCALE(LOC_ID_C) values('ga');
insert into T_LOCALE(LOC_ID_C) values('it_IT');
insert into T_LOCALE(LOC_ID_C) values('it_CH');
insert into T_LOCALE(LOC_ID_C) values('it');
insert into T_LOCALE(LOC_ID_C) values('ja_JP');
insert into T_LOCALE(LOC_ID_C) values('ja_JP_JP');
insert into T_LOCALE(LOC_ID_C) values('ja');
insert into T_LOCALE(LOC_ID_C) values('ko_KR');
insert into T_LOCALE(LOC_ID_C) values('ko');
insert into T_LOCALE(LOC_ID_C) values('lv_LV');
insert into T_LOCALE(LOC_ID_C) values('lv');
insert into T_LOCALE(LOC_ID_C) values('lt_LT');
insert into T_LOCALE(LOC_ID_C) values('lt');
insert into T_LOCALE(LOC_ID_C) values('mk_MK');
insert into T_LOCALE(LOC_ID_C) values('mk');
insert into T_LOCALE(LOC_ID_C) values('ms_MY');
insert into T_LOCALE(LOC_ID_C) values('ms');
insert into T_LOCALE(LOC_ID_C) values('mt_MT');
insert into T_LOCALE(LOC_ID_C) values('mt');
insert into T_LOCALE(LOC_ID_C) values('no_NO');
insert into T_LOCALE(LOC_ID_C) values('no_NO_NY');
insert into T_LOCALE(LOC_ID_C) values('no');
insert into T_LOCALE(LOC_ID_C) values('pl_PL');
insert into T_LOCALE(LOC_ID_C) values('pl');
insert into T_LOCALE(LOC_ID_C) values('pt_BR');
insert into T_LOCALE(LOC_ID_C) values('pt_PT');
insert into T_LOCALE(LOC_ID_C) values('pt');
insert into T_LOCALE(LOC_ID_C) values('ro_RO');
insert into T_LOCALE(LOC_ID_C) values('ro');
insert into T_LOCALE(LOC_ID_C) values('ru_RU');
insert into T_LOCALE(LOC_ID_C) values('ru');
insert into T_LOCALE(LOC_ID_C) values('sr_BA');
insert into T_LOCALE(LOC_ID_C) values('sr_ME');
insert into T_LOCALE(LOC_ID_C) values('sr_CS');
insert into T_LOCALE(LOC_ID_C) values('sr_RS');
insert into T_LOCALE(LOC_ID_C) values('sr');
insert into T_LOCALE(LOC_ID_C) values('sk_SK');
insert into T_LOCALE(LOC_ID_C) values('sk');
insert into T_LOCALE(LOC_ID_C) values('sl_SI');
insert into T_LOCALE(LOC_ID_C) values('sl');
insert into T_LOCALE(LOC_ID_C) values('es_AR');
insert into T_LOCALE(LOC_ID_C) values('es_BO');
insert into T_LOCALE(LOC_ID_C) values('es_CL');
insert into T_LOCALE(LOC_ID_C) values('es_CO');
insert into T_LOCALE(LOC_ID_C) values('es_CR');
insert into T_LOCALE(LOC_ID_C) values('es_DO');
insert into T_LOCALE(LOC_ID_C) values('es_EC');
insert into T_LOCALE(LOC_ID_C) values('es_SV');
insert into T_LOCALE(LOC_ID_C) values('es_GT');
insert into T_LOCALE(LOC_ID_C) values('es_HN');
insert into T_LOCALE(LOC_ID_C) values('es_MX');
insert into T_LOCALE(LOC_ID_C) values('es_NI');
insert into T_LOCALE(LOC_ID_C) values('es_PA');
insert into T_LOCALE(LOC_ID_C) values('es_PY');
insert into T_LOCALE(LOC_ID_C) values('es_PE');
insert into T_LOCALE(LOC_ID_C) values('es_PR');
insert into T_LOCALE(LOC_ID_C) values('es_ES');
insert into T_LOCALE(LOC_ID_C) values('es_US');
insert into T_LOCALE(LOC_ID_C) values('es_UY');
insert into T_LOCALE(LOC_ID_C) values('es_VE');
insert into T_LOCALE(LOC_ID_C) values('es');
insert into T_LOCALE(LOC_ID_C) values('sv_SE');
insert into T_LOCALE(LOC_ID_C) values('sv');
insert into T_LOCALE(LOC_ID_C) values('th_TH');
insert into T_LOCALE(LOC_ID_C) values('th_TH_TH');
insert into T_LOCALE(LOC_ID_C) values('th');
insert into T_LOCALE(LOC_ID_C) values('tr_TR');
insert into T_LOCALE(LOC_ID_C) values('tr');
insert into T_LOCALE(LOC_ID_C) values('uk_UA');
insert into T_LOCALE(LOC_ID_C) values('uk');
insert into T_LOCALE(LOC_ID_C) values('vi_VN');
insert into T_LOCALE(LOC_ID_C) values('vi');

-- Administrator: Username/initial password=admin/admin
insert into T_USER(USE_ID_C, USE_IDLOCALE_C, USE_USERNAME_C, USE_PASSWORD_C, USE_EMAIL_C, USE_DISPLAYTITLEWEB_B, USE_DISPLAYTITLEMOBILE_B, USE_DISPLAYUNREADWEB_B, USE_DISPLAYUNREADMOBILE_B, USE_CREATEDATE_D) values('admin', 'en', 'admin', '$2a$05$6Ny3TjrW3aVAL1or2SlcR.fhuDgPKp5jp.P9fBXwVNePgeLqb4i3C', 'admin@localhost', false, true, true, true, NOW());
-- Test users: Password=12345678
insert into T_USER(USE_ID_C, USE_IDLOCALE_C, USE_USERNAME_C, USE_PASSWORD_C, USE_EMAIL_C, USE_DISPLAYTITLEWEB_B, USE_DISPLAYTITLEMOBILE_B, USE_DISPLAYUNREADWEB_B, USE_DISPLAYUNREADMOBILE_B, USE_CREATEDATE_D) values('user', 'fr_FR', 'user', '$2a$10$sz0CcBs45prABgQbN5oK1uQJyGDV2i/AK8RJC8QEVfjxVxtCj7kGW', 'user@localhost', false, true, true, true, NOW());
insert into T_USER(USE_ID_C, USE_IDLOCALE_C, USE_USERNAME_C, USE_PASSWORD_C, USE_EMAIL_C, USE_DISPLAYTITLEWEB_B, USE_DISPLAYTITLEMOBILE_B, USE_DISPLAYUNREADWEB_B, USE_DISPLAYUNREADMOBILE_B, USE_CREATEDATE_D) values('user1', 'en', 'user1', '$2a$10$sz0CcBs45prABgQbN5oK1uQJyGDV2i/AK8RJC8QEVfjxVxtCj7kGW', 'user1@localhost', false, true, true, true, NOW());
insert into T_USER(USE_ID_C, USE_IDLOCALE_C, USE_USERNAME_C, USE_PASSWORD_C, USE_EMAIL_C, USE_DISPLAYTITLEWEB_B, USE_DISPLAYTITLEMOBILE_B, USE_DISPLAYUNREADWEB_B, USE_DISPLAYUNREADMOBILE_B, USE_CREATEDATE_D) values('user2', 'fr_FR', 'user2', '$2a$10$sz0CcBs45prABgQbN5oK1uQJyGDV2i/AK8RJC8QEVfjxVxtCj7kGW', 'user2@localhost', false, true, true, true, NOW());

insert into T_USER_BASE_FUNCTION(UBF_ID_C, UBF_IDUSER_C, UBF_IDBASEFUNCTION_C, UBF_CREATEDATE_D) values('admin_ADMIN', 'admin', 'ADMIN', NOW());

insert into T_FEED(FED_ID_C, FED_RSSURL_C, FED_URL_C, FED_TITLE_C, FED_DESCRIPTION_C, FED_CREATEDATE_D) values('space', 'http://www.space.com/home/feed/site.xml', 'http://www.space.com/', 'SPACE.com', 'Something amazing every day.', NOW());
insert into T_FEED(FED_ID_C, FED_RSSURL_C, FED_URL_C, FED_TITLE_C, FED_DESCRIPTION_C, FED_CREATEDATE_D) values('slashdot', 'http://rss.slashdot.org/Slashdot/slashdot', 'http://slashdot.org/', 'Slashdot', 'News for nerds, stuff that matters', NOW());
insert into T_FEED(FED_ID_C, FED_RSSURL_C, FED_URL_C, FED_TITLE_C, FED_DESCRIPTION_C, FED_CREATEDATE_D) values('techcrunch', 'http://feeds.feedburner.com/TechCrunch', 'http://techcrunch.com', 'TechCrunch', 'TechCrunch is a group-edited blog that profiles the companies, products and events defining and transforming the new web.', NOW());
insert into T_FEED(FED_ID_C, FED_RSSURL_C, FED_URL_C, FED_TITLE_C, FED_DESCRIPTION_C, FED_CREATEDATE_D) values('xkcd', 'http://xkcd.com/rss.xml', 'http://xkcd.com/', 'xkcd.com', 'xkcd.com: A webcomic of romance and math humor.', NOW());

insert into T_CATEGORY(CAT_ID_C, CAT_IDUSER_C, CAT_IDPARENT_C, CAT_NAME_C, CAT_ORDER_N, CAT_FOLDED_B, CAT_CREATEDATE_D) values('admin-root', 'admin', null, null, 0, false, NOW());
insert into T_CATEGORY(CAT_ID_C, CAT_IDUSER_C, CAT_IDPARENT_C, CAT_NAME_C, CAT_ORDER_N, CAT_FOLDED_B, CAT_CREATEDATE_D) values('user-root', 'user', null, null, 0, false, NOW());
insert into T_CATEGORY(CAT_ID_C, CAT_IDUSER_C, CAT_IDPARENT_C, CAT_NAME_C, CAT_ORDER_N, CAT_FOLDED_B, CAT_CREATEDATE_D) values('user1-root', 'user1', null, null, 0, false, NOW());
insert into T_CATEGORY(CAT_ID_C, CAT_IDUSER_C, CAT_IDPARENT_C, CAT_NAME_C, CAT_ORDER_N, CAT_FOLDED_B, CAT_CREATEDATE_D) values('user2-root', 'user2', null, null, 0, false, NOW());
insert into T_CATEGORY(CAT_ID_C, CAT_IDUSER_C, CAT_IDPARENT_C, CAT_NAME_C, CAT_ORDER_N, CAT_FOLDED_B, CAT_CREATEDATE_D) values('user1-technology', 'user1', 'user1-root', 'Technology', 0, false, NOW());
insert into T_CATEGORY(CAT_ID_C, CAT_IDUSER_C, CAT_IDPARENT_C, CAT_NAME_C, CAT_ORDER_N, CAT_FOLDED_B, CAT_CREATEDATE_D) values('user1-comics', 'user1', 'user1-root', 'Comics', 1, false, NOW());

insert into T_FEED_SUBSCRIPTION(FES_ID_C, FES_IDUSER_C, FES_IDFEED_C, FES_IDCATEGORY_C, FES_ORDER_N, FES_CREATEDATE_D) values('user1-space', 'user1', 'space', 'user1-root', 0, NOW());
insert into T_FEED_SUBSCRIPTION(FES_ID_C, FES_IDUSER_C, FES_IDFEED_C, FES_IDCATEGORY_C, FES_ORDER_N, FES_CREATEDATE_D) values('user1-slashdot', 'user1', 'slashdot', 'user1-technology', 0, NOW());
insert into T_FEED_SUBSCRIPTION(FES_ID_C, FES_IDUSER_C, FES_IDFEED_C, FES_IDCATEGORY_C, FES_ORDER_N, FES_CREATEDATE_D) values('user1-techcrunch', 'user1', 'techcrunch', 'user1-technology', 1, NOW());
insert into T_FEED_SUBSCRIPTION(FES_ID_C, FES_IDUSER_C, FES_IDFEED_C, FES_IDCATEGORY_C, FES_ORDER_N, FES_CREATEDATE_D) values('user1-xkcd', 'user1', 'xkcd', 'user1-comics', 0, NOW());
