#!/bin/sh

# Stop Reader service.
if [ -e /etc/init.d/reader ]; then
  service reader stop
fi

# Backup database.
if [ -e /var/reader/db ]; then
  rm -rf /var/reader/db.backup
  cp -R /var/reader/db /var/reader/db.backup
fi

exit 0
